import { Supplier, SuggestedItem } from './types';

export const initialSuppliers: Supplier[] = [
  {
    id: 'llp',
    name: 'LLPsuperstore',
    minimumOrderValue: 800,
    currentTotal: 325.34,
    items: [
      {
        id: 'item-1',
        name: 'Coca-Cola Original Taste',
        description: '24X330ml',
        price: 75.20,
        originalPrice: 118.20,
        unitPrice: '11.8/unit',
        quantity: 4,
        image: '/images/product-cocacola.svg',
        supplierId: 'llp',
      },
      {
        id: 'item-2',
        name: 'Basmati Premium Rice',
        description: '5kg bag',
        price: 150.00,
        unitPrice: '30.0/kg',
        quantity: 2,
        image: '/images/product-rice.svg',
        supplierId: 'llp',
      },
      {
        id: 'item-3',
        name: 'Golden Vegetable Oil',
        description: '5L bottle',
        price: 100.14,
        unitPrice: '20.0/L',
        quantity: 3,
        image: '/images/product-oil.svg',
        supplierId: 'llp',
      },
    ],
  },
  {
    id: 'sup2',
    name: 'Supplier#2',
    minimumOrderValue: 800,
    currentTotal: 343.20,
    items: [
      {
        id: 'item-4',
        name: 'Fresh Whole Milk',
        description: '1 Litre',
        price: 75.20,
        originalPrice: 118.20,
        unitPrice: '75.2/L',
        quantity: 1,
        image: '/images/product-milk.svg',
        supplierId: 'sup2',
      },
      {
        id: 'item-5',
        name: 'Spaghetti Pasta',
        description: '500g pack',
        price: 118.20,
        unitPrice: '236.4/kg',
        quantity: 1,
        image: '/images/product-pasta.svg',
        supplierId: 'sup2',
      },
      {
        id: 'item-6',
        name: 'Tropicana Orange Juice',
        description: '1 Litre carton',
        price: 150.00,
        unitPrice: '150.0/L',
        quantity: 1,
        image: '/images/product-juice.svg',
        supplierId: 'sup2',
      },
    ],
  },
  {
    id: 'sup3',
    name: 'Supplier#3',
    minimumOrderValue: 800,
    currentTotal: 0,
    items: [
      {
        id: 'item-7',
        name: 'Spring Water',
        description: '500ml X24',
        price: 75.20,
        unitPrice: '3.1/bottle',
        quantity: 1,
        image: '/images/product-water.svg',
        supplierId: 'sup3',
      },
      {
        id: 'item-8',
        name: 'Classic Salted Chips',
        description: '150g bag',
        price: 118.20,
        unitPrice: '78.8/100g',
        quantity: 1,
        image: '/images/product-chips.svg',
        supplierId: 'sup3',
      },
    ],
  },
];

export const suggestedItems: SuggestedItem[] = [
  {
    id: 'sug-1',
    supplier: 'LLPsuperstore',
    name: 'Fresh Whole Milk',
    description: '1 Litre',
    price: 3.42,
    unitPrice: '3.42/L',
    image: '/images/product-milk.svg',
  },
  {
    id: 'sug-2',
    supplier: 'LLPsuperstore',
    name: 'Tropicana Orange Juice',
    description: '1L carton',
    price: 5.99,
    unitPrice: '5.99/L',
    image: '/images/product-juice.svg',
  },
  {
    id: 'sug-3',
    supplier: 'Supplier#2',
    name: 'Spring Water',
    description: '500ml X24',
    price: 8.50,
    unitPrice: '0.35/bottle',
    image: '/images/product-water.svg',
  },
  {
    id: 'sug-4',
    supplier: 'Supplier#2',
    name: 'Classic Salted Chips',
    description: '150g bag',
    price: 2.75,
    unitPrice: '1.83/100g',
    image: '/images/product-chips.svg',
  },
];
