/* ═══════════════════════════════════════════════════════════
   Home & Search — Shared Data
   ═══════════════════════════════════════════════════════════ */

export interface HomeProduct {
  id: string;
  supplier: string;
  name: string;
  description: string;
  options?: string;
  price: number;
  originalPrice?: number;
  unitPrice: string;
  image: string;
  pricingOptions?: number;
}

export interface Category {
  id: string;
  name: string;
  subcategories: SubCategory[];
}

export interface SubCategory {
  id: string;
  name: string;
}

/* ── Homepage product sections ── */

export const promotions: HomeProduct[] = [
  {
    id: 'promo-1',
    supplier: 'GreatValue',
    name: 'Great Value Frosted Bite Size Shredded Wheat Cereal',
    description: '24 oz',
    options: 'More sizes & flavours',
    price: 2.82,
    originalPrice: 3.00,
    unitPrice: '11.5/unit',
    image: '/images/wonder-bread.svg',
    pricingOptions: 6,
  },
  {
    id: 'promo-2',
    supplier: "Kellogg's",
    name: "Kellogg's Frosted Flakes Cereal",
    description: '18 oz',
    options: 'More sizes & flavours',
    price: 3.50,
    originalPrice: 4.00,
    unitPrice: '19.4/unit',
    image: '/images/wonder-bread.svg',
    pricingOptions: 6,
  },
  {
    id: 'promo-3',
    supplier: 'Cheerios',
    name: 'Cheerios Original Cereal',
    description: '18 oz',
    options: 'More sizes & flavours',
    price: 5.29,
    originalPrice: 5.99,
    unitPrice: '29.4/unit',
    image: '/images/wonder-bread.svg',
    pricingOptions: 6,
  },
  {
    id: 'promo-4',
    supplier: 'Post',
    name: 'Post Grape-Nuts Cereal',
    description: '18 oz',
    options: 'More sizes & flavours',
    price: 4.49,
    originalPrice: 5.00,
    unitPrice: '24.9/unit',
    image: '/images/wonder-bread.svg',
    pricingOptions: 6,
  },
  {
    id: 'promo-5',
    supplier: 'Quaker',
    name: 'Quaker Oatmeal Squares',
    description: '18 oz',
    options: 'More sizes & flavours',
    price: 4.99,
    originalPrice: 5.50,
    unitPrice: '27.7/unit',
    image: '/images/wonder-bread.svg',
    pricingOptions: 6,
  },
  {
    id: 'promo-6',
    supplier: 'Nature Valley',
    name: 'Nature Valley Granola Cereal',
    description: '11.5 oz',
    options: 'More sizes & flavours',
    price: 4.99,
    originalPrice: 5.50,
    unitPrice: '43.4/unit',
    image: '/images/wonder-bread.svg',
    pricingOptions: 6,
  },
  {
    id: 'promo-7',
    supplier: 'HealthyChoice',
    name: 'Organic Whole Grain Oats',
    description: '32 oz',
    options: 'More sizes & flavours',
    price: 3.50,
    originalPrice: 4.00,
    unitPrice: '10.9/unit',
    image: '/images/wonder-bread.svg',
    pricingOptions: 6,
  },
];

export const mostSold: HomeProduct[] = [
  {
    id: 'sold-1',
    supplier: 'GreatValue',
    name: 'Great Value Frosted Bite Size Shredded Wheat Cereal',
    description: '24 oz',
    options: 'More sizes & flavours',
    price: 2.82,
    originalPrice: 3.00,
    unitPrice: '11.5/unit',
    image: '/images/wonder-bread.svg',
    pricingOptions: 6,
  },
  {
    id: 'sold-2',
    supplier: "Kellogg's",
    name: "Kellogg's Frosted Mini-Wheats Cereal",
    description: '18 oz',
    options: 'More sizes',
    price: 3.49,
    originalPrice: 3.99,
    unitPrice: '19.4/unit',
    image: '/images/wonder-bread.svg',
    pricingOptions: 6,
  },
  {
    id: 'sold-3',
    supplier: 'Post',
    name: 'Post Honey Bunches of Oats Cereal',
    description: '13 oz',
    options: 'More sizes & flavours',
    price: 3.29,
    originalPrice: 3.79,
    unitPrice: '25.3/unit',
    image: '/images/wonder-bread.svg',
    pricingOptions: 6,
  },
  {
    id: 'sold-4',
    supplier: 'General Mills',
    name: 'Cheerios Cereal',
    description: '12 oz',
    options: 'More sizes',
    price: 3.15,
    originalPrice: 5.50,
    unitPrice: '26.3/unit',
    image: '/images/wonder-bread.svg',
    pricingOptions: 6,
  },
  {
    id: 'sold-5',
    supplier: 'Quaker',
    name: 'Quaker Oatmeal Squares, Cinnamon',
    description: '14 oz',
    options: 'More sizes & flavours',
    price: 4.50,
    originalPrice: 4.99,
    unitPrice: '32.1/unit',
    image: '/images/wonder-bread.svg',
    pricingOptions: 6,
  },
  {
    id: 'sold-6',
    supplier: 'Nature Valley',
    name: "Nature Valley Crunchy Granola, Oats 'n Honey",
    description: '12 oz',
    options: 'More sizes & flavours',
    price: 3.99,
    originalPrice: 4.29,
    unitPrice: '33.3/unit',
    image: '/images/wonder-bread.svg',
    pricingOptions: 6,
  },
  {
    id: 'sold-7',
    supplier: 'NutriMunch',
    name: 'Crispy Brown Rice Snacks',
    description: '8 oz',
    options: 'More sizes & flavours',
    price: 1.99,
    originalPrice: 2.20,
    unitPrice: '24.9/unit',
    image: '/images/wonder-bread.svg',
    pricingOptions: 6,
  },
];

export const newArrivals: HomeProduct[] = [
  {
    id: 'new-1',
    supplier: 'GreatValue',
    name: 'Great Value Frosted Bite Size Shredded Wheat Cereal',
    description: '24 oz',
    options: 'More sizes & flavours',
    price: 2.82,
    originalPrice: 3.00,
    unitPrice: '11.5/unit',
    image: '/images/wonder-bread.svg',
    pricingOptions: 6,
  },
  {
    id: 'new-2',
    supplier: 'HealthyChoice',
    name: 'Organic Whole Grain Oats',
    description: '32 oz',
    options: 'More sizes & flavours',
    price: 3.50,
    originalPrice: 4.00,
    unitPrice: '10.9/unit',
    image: '/images/wonder-bread.svg',
    pricingOptions: 6,
  },
  {
    id: 'new-3',
    supplier: 'NutriMunch',
    name: 'Crispy Brown Rice Snacks',
    description: '8 oz',
    options: 'More sizes & flavours',
    price: 1.99,
    originalPrice: 2.20,
    unitPrice: '24.9/unit',
    image: '/images/wonder-bread.svg',
    pricingOptions: 6,
  },
  {
    id: 'new-4',
    supplier: 'SunnyDales',
    name: 'Organic Mixed Fruit Snacks',
    description: '10 oz',
    options: 'More sizes & flavours',
    price: 3.25,
    originalPrice: 3.50,
    unitPrice: '32.5/unit',
    image: '/images/wonder-bread.svg',
    pricingOptions: 6,
  },
  {
    id: 'new-5',
    supplier: 'PureEssentials',
    name: 'Almond Butter',
    description: '16 oz',
    options: 'More sizes & flavours',
    price: 6.99,
    originalPrice: 7.50,
    unitPrice: '43.7/unit',
    image: '/images/wonder-bread.svg',
    pricingOptions: 6,
  },
  {
    id: 'new-6',
    supplier: 'SnackSmart',
    name: 'Kale Chips',
    description: '5 oz',
    options: 'More sizes & flavours',
    price: 4.49,
    originalPrice: 4.99,
    unitPrice: '89.8/unit',
    image: '/images/wonder-bread.svg',
    pricingOptions: 6,
  },
  {
    id: 'new-7',
    supplier: 'LLPsuperstore',
    name: 'Coca-Cola Original Taste',
    description: '24X330ml',
    options: 'Options: 3 sizes, 2 Flavours',
    price: 2.82,
    originalPrice: 3.00,
    unitPrice: '11.5/unit',
    image: '/images/product-cocacola.svg',
    pricingOptions: 6,
  },
];

/* ── Categories + subcategories ── */

export const categories: Category[] = [
  {
    id: 'warehouse',
    name: 'Warehouse',
    subcategories: [
      { id: 'ws-all', name: 'Shop All' },
      { id: 'ws-bulk', name: 'Bulk Items' },
      { id: 'ws-cleaning', name: 'Cleaning Supplies' },
    ],
  },
  {
    id: 'drinks',
    name: 'Drinks',
    subcategories: [
      { id: 'dr-all', name: 'Shop All' },
      { id: 'dr-beers', name: 'Beers' },
      { id: 'dr-wines', name: 'Wines and Sparkling Wines' },
      { id: 'dr-white', name: 'White Drinks' },
      { id: 'dr-fernet', name: 'Fernet and Aperitifs' },
      { id: 'dr-soft', name: 'Soft Drinks' },
      { id: 'dr-water', name: 'Water' },
      { id: 'dr-flavoured', name: 'Flavoured Water' },
      { id: 'dr-juices', name: 'Juices' },
      { id: 'dr-isotonic', name: 'Isotonic Drinks' },
      { id: 'dr-energy', name: 'Energising Drinks' },
      { id: 'dr-others', name: 'Others' },
    ],
  },
  {
    id: 'dairy',
    name: 'Dairy and Fresh Products',
    subcategories: [
      { id: 'da-all', name: 'Shop All' },
      { id: 'da-milk', name: 'Milk' },
      { id: 'da-cheese', name: 'Cheese' },
      { id: 'da-yogurt', name: 'Yogurt' },
    ],
  },
  {
    id: 'frozen',
    name: 'Frozen Products',
    subcategories: [
      { id: 'fr-all', name: 'Shop All' },
      { id: 'fr-icecream', name: 'Ice Cream' },
      { id: 'fr-meals', name: 'Frozen Meals' },
    ],
  },
  {
    id: 'cleaning',
    name: 'Cleaning',
    subcategories: [
      { id: 'cl-all', name: 'Shop All' },
      { id: 'cl-laundry', name: 'Laundry' },
      { id: 'cl-kitchen', name: 'Kitchen' },
    ],
  },
  {
    id: 'meat',
    name: 'Meat and Fish',
    subcategories: [
      { id: 'mt-all', name: 'Shop All' },
      { id: 'mt-beef', name: 'Beef' },
      { id: 'mt-chicken', name: 'Chicken' },
      { id: 'mt-fish', name: 'Fish' },
    ],
  },
  {
    id: 'fruits',
    name: 'Fruits and Vegetables',
    subcategories: [
      { id: 'fv-all', name: 'Shop All' },
      { id: 'fv-fruits', name: 'Fruits' },
      { id: 'fv-vegetables', name: 'Vegetables' },
    ],
  },
  {
    id: 'bakery',
    name: 'Bakery',
    subcategories: [
      { id: 'bk-all', name: 'Shop All' },
      { id: 'bk-bread', name: 'Bread' },
      { id: 'bk-pastry', name: 'Pastries' },
    ],
  },
  {
    id: 'perfumery',
    name: 'Perfumery',
    subcategories: [
      { id: 'pf-all', name: 'Shop All' },
    ],
  },
  {
    id: 'baby',
    name: 'Baby World',
    subcategories: [
      { id: 'bw-all', name: 'Shop All' },
    ],
  },
  {
    id: 'others',
    name: 'Others',
    subcategories: [
      { id: 'ot-all', name: 'Shop All' },
    ],
  },
  {
    id: 'pets',
    name: 'Pet Supplies',
    subcategories: [
      { id: 'ps-all', name: 'Shop All' },
    ],
  },
  {
    id: 'books',
    name: 'Books and Stationery',
    subcategories: [
      { id: 'bs-all', name: 'Shop All' },
    ],
  },
];

/* ── Search/Category product listing (shared pool) ── */

export const categoryProducts: HomeProduct[] = [
  {
    id: 'cat-1',
    supplier: 'GreatValue',
    name: 'Coca-Cola Original Taste',
    description: '24 x 330ml',
    options: 'More sizes & flavours',
    price: 2.82,
    originalPrice: 3.00,
    unitPrice: '11.8 ¢/oz',
    image: '/images/wonder-bread.svg',
    pricingOptions: 6,
  },
  {
    id: 'cat-2',
    supplier: 'GreatValue',
    name: 'Coca-Cola Original Taste',
    description: '24 x 330ml',
    options: 'More sizes & flavours',
    price: 2.82,
    originalPrice: 3.00,
    unitPrice: '11.8 ¢/oz',
    image: '/images/wonder-bread.svg',
    pricingOptions: 6,
  },
  {
    id: 'cat-3',
    supplier: 'GreatValue',
    name: 'Coca-Cola Original Taste',
    description: '24 x 330ml',
    options: 'More sizes & flavours',
    price: 2.82,
    originalPrice: 3.00,
    unitPrice: '11.8 ¢/oz',
    image: '/images/wonder-bread.svg',
    pricingOptions: 6,
  },
  {
    id: 'cat-4',
    supplier: 'GreatValue',
    name: 'Coca-Cola Original Taste',
    description: '24 x 330ml',
    options: 'More sizes & flavours',
    price: 2.82,
    originalPrice: 3.00,
    unitPrice: '11.8 ¢/oz',
    image: '/images/wonder-bread.svg',
    pricingOptions: 6,
  },
  {
    id: 'cat-5',
    supplier: 'LLPsuperstore',
    name: 'Coca-Cola Original Taste',
    description: '24 x 330ml',
    options: 'Options: 3 sizes, 2 Flavours',
    price: 2.82,
    originalPrice: 3.00,
    unitPrice: '11.5/unit',
    image: '/images/product-cocacola.svg',
    pricingOptions: 6,
  },
  {
    id: 'cat-6',
    supplier: 'LLPsuperstore',
    name: 'Coca-Cola Original Taste',
    description: '24 x 330ml',
    options: 'Options: 3 sizes, 2 Flavours',
    price: 2.82,
    originalPrice: 3.00,
    unitPrice: '11.5/unit',
    image: '/images/product-cocacola.svg',
    pricingOptions: 6,
  },
  {
    id: 'cat-7',
    supplier: 'LLPsuperstore',
    name: 'Coca-Cola Original Taste',
    description: '24 x 330ml',
    options: 'Options: 3 sizes, 2 Flavours',
    price: 2.82,
    originalPrice: 3.00,
    unitPrice: '11.5/unit',
    image: '/images/product-cocacola.svg',
    pricingOptions: 6,
  },
  {
    id: 'cat-8',
    supplier: 'LLPsuperstore',
    name: 'Coca-Cola Original Taste',
    description: '24 x 330ml',
    options: 'Options: 3 sizes, 2 Flavours',
    price: 2.82,
    originalPrice: 3.00,
    unitPrice: '11.5/unit',
    image: '/images/product-cocacola.svg',
    pricingOptions: 6,
  },
  {
    id: 'cat-9',
    supplier: 'LLPsuperstore',
    name: 'Coca-Cola Original Taste',
    description: '24 x 330ml',
    options: 'Options: 3 sizes, 2 Flavours',
    price: 2.82,
    originalPrice: 3.00,
    unitPrice: '11.5/unit',
    image: '/images/product-cocacola.svg',
    pricingOptions: 6,
  },
  {
    id: 'cat-10',
    supplier: 'LLPsuperstore',
    name: 'Coca-Cola Original Taste',
    description: '24 x 330ml',
    options: 'Options: 3 sizes, 2 Flavours',
    price: 2.82,
    originalPrice: 3.00,
    unitPrice: '11.5/unit',
    image: '/images/product-cocacola.svg',
    pricingOptions: 6,
  },
  {
    id: 'cat-11',
    supplier: 'LLPsuperstore',
    name: 'Coca-Cola Original Taste',
    description: '24 x 330ml',
    options: 'Options: 3 sizes, 2 Flavours',
    price: 2.82,
    originalPrice: 3.00,
    unitPrice: '11.5/unit',
    image: '/images/product-cocacola.svg',
    pricingOptions: 6,
  },
  {
    id: 'cat-12',
    supplier: 'LLPsuperstore',
    name: 'Coca-Cola Original Taste',
    description: '24 x 330ml',
    options: 'Options: 3 sizes, 2 Flavours',
    price: 2.82,
    originalPrice: 3.00,
    unitPrice: '11.5/unit',
    image: '/images/product-cocacola.svg',
    pricingOptions: 6,
  },
];

/* ── Beverages subcategories (for search page demo) ── */

export const beverageSubcategories: SubCategory[] = [
  { id: 'bev-water', name: 'Water' },
  { id: 'bev-soda', name: 'Soda' },
  { id: 'bev-juices', name: 'Juices' },
  { id: 'bev-kids', name: 'Kids Drink & Juice Box' },
  { id: 'bev-sports', name: 'Sport Drinks' },
  { id: 'bev-tea', name: 'Tea' },
  { id: 'bev-mix', name: 'Drink Mix' },
];
