/* ═══════════════════════════════════════════════════════════
   Home & Search — Shared Data
   ═══════════════════════════════════════════════════════════ */

export interface HomeProduct {
  id: string;
  supplier: string;
  name: string;
  description: string;
  options?: string;
  price: number;
  originalPrice?: number;
  unitPrice: string;
  image: string;
  pricingOptions?: number;
}

export interface Category {
  id: string;
  name: string;
  subcategories: SubCategory[];
}

export interface SubCategory {
  id: string;
  name: string;
}

/* ── Homepage product sections ── */

export const promotions: HomeProduct[] = [
  {
    id: 'promo-1',
    supplier: 'LLPsuperstore',
    name: 'Coca-Cola Original Taste',
    description: '24 x 330ml',
    options: 'Options: 3 sizes, 2 Flavours',
    price: 8.99,
    originalPrice: 12.50,
    unitPrice: '11.5/unit',
    image: '/images/product-cocacola.svg',
    pricingOptions: 6,
  },
  {
    id: 'promo-2',
    supplier: 'GreatValue',
    name: 'Sunflower Vegetable Oil',
    description: '1.5 Litres',
    options: 'More sizes',
    price: 3.49,
    originalPrice: 4.20,
    unitPrice: '2.33/L',
    image: '/images/product-oil.svg',
    pricingOptions: 3,
  },
  {
    id: 'promo-3',
    supplier: 'FreshFarms',
    name: 'Full Cream Milk',
    description: '1 Litre',
    options: 'More sizes',
    price: 1.29,
    originalPrice: 1.69,
    unitPrice: '1.29/L',
    image: '/images/product-milk.svg',
    pricingOptions: 4,
  },
  {
    id: 'promo-4',
    supplier: 'Del Monte',
    name: 'Orange Juice, No Pulp',
    description: '1 Litre',
    options: 'More flavours',
    price: 2.99,
    originalPrice: 3.80,
    unitPrice: '2.99/L',
    image: '/images/product-juice.svg',
    pricingOptions: 5,
  },
  {
    id: 'promo-5',
    supplier: 'NutriGrain',
    name: 'Long Grain Basmati Rice',
    description: '5 kg',
    options: 'More sizes',
    price: 6.49,
    originalPrice: 8.00,
    unitPrice: '1.30/kg',
    image: '/images/product-rice.svg',
    pricingOptions: 3,
  },
  {
    id: 'promo-6',
    supplier: 'Barilla',
    name: 'Spaghetti No.5',
    description: '500g',
    options: 'More sizes & types',
    price: 1.89,
    originalPrice: 2.40,
    unitPrice: '3.78/kg',
    image: '/images/product-pasta.svg',
    pricingOptions: 6,
  },
  {
    id: 'promo-7',
    supplier: 'AquaPure',
    name: 'Natural Spring Water',
    description: '6 x 1.5L',
    options: 'More sizes',
    price: 3.50,
    originalPrice: 4.20,
    unitPrice: '0.39/L',
    image: '/images/product-water.svg',
    pricingOptions: 4,
  },
];

export const mostSold: HomeProduct[] = [
  {
    id: 'sold-1',
    supplier: 'Wonder',
    name: 'Classic White Bread',
    description: '20 oz Loaf',
    options: 'More types',
    price: 2.49,
    originalPrice: 2.99,
    unitPrice: '12.5¢/oz',
    image: '/images/wonder-bread.svg',
    pricingOptions: 4,
  },
  {
    id: 'sold-2',
    supplier: 'LLPsuperstore',
    name: 'Coca-Cola Zero Sugar',
    description: '12 x 330ml',
    options: 'Options: 3 sizes, 2 Flavours',
    price: 5.99,
    originalPrice: 7.20,
    unitPrice: '0.50/can',
    image: '/images/product-cocacola.svg',
    pricingOptions: 6,
  },
  {
    id: 'sold-3',
    supplier: 'FreshFarms',
    name: 'Semi-Skimmed Milk',
    description: '2 Litres',
    options: 'More sizes',
    price: 2.15,
    originalPrice: 2.60,
    unitPrice: '1.08/L',
    image: '/images/product-milk.svg',
    pricingOptions: 3,
  },
  {
    id: 'sold-4',
    supplier: "Lay's",
    name: "Classic Potato Chips",
    description: '200g',
    options: 'More flavours',
    price: 3.29,
    originalPrice: 3.99,
    unitPrice: '16.5/kg',
    image: '/images/product-chips.svg',
    pricingOptions: 8,
  },
  {
    id: 'sold-5',
    supplier: 'GreatValue',
    name: 'Sunflower Vegetable Oil',
    description: '3 Litres',
    options: 'More sizes',
    price: 5.99,
    originalPrice: 7.50,
    unitPrice: '2.00/L',
    image: '/images/product-oil.svg',
    pricingOptions: 3,
  },
  {
    id: 'sold-6',
    supplier: 'Barilla',
    name: 'Penne Rigate Pasta',
    description: '1 kg',
    options: 'More types',
    price: 2.99,
    originalPrice: 3.50,
    unitPrice: '2.99/kg',
    image: '/images/product-pasta.svg',
    pricingOptions: 6,
  },
  {
    id: 'sold-7',
    supplier: 'NutriGrain',
    name: 'Jasmine Rice',
    description: '2 kg',
    options: 'More sizes',
    price: 4.29,
    originalPrice: 5.00,
    unitPrice: '2.15/kg',
    image: '/images/product-rice.svg',
    pricingOptions: 3,
  },
];

export const newArrivals: HomeProduct[] = [
  {
    id: 'new-1',
    supplier: 'Del Monte',
    name: 'Tropical Fruit Juice Blend',
    description: '1.5 Litres',
    options: 'More flavours',
    price: 3.79,
    originalPrice: 4.50,
    unitPrice: '2.53/L',
    image: '/images/product-juice.svg',
    pricingOptions: 5,
  },
  {
    id: 'new-2',
    supplier: "Lay's",
    name: "BBQ Flavour Potato Chips",
    description: '150g',
    options: 'More flavours',
    price: 2.79,
    originalPrice: 3.29,
    unitPrice: '18.6/kg',
    image: '/images/product-chips.svg',
    pricingOptions: 8,
  },
  {
    id: 'new-3',
    supplier: 'AquaPure',
    name: 'Sparkling Mineral Water',
    description: '12 x 500ml',
    options: 'More sizes',
    price: 4.99,
    originalPrice: 6.00,
    unitPrice: '0.42/bottle',
    image: '/images/product-water.svg',
    pricingOptions: 4,
  },
  {
    id: 'new-4',
    supplier: 'Wonder',
    name: 'Whole Wheat Bread',
    description: '24 oz Loaf',
    options: 'More types',
    price: 3.19,
    originalPrice: 3.79,
    unitPrice: '13.3¢/oz',
    image: '/images/wonder-bread.svg',
    pricingOptions: 4,
  },
  {
    id: 'new-5',
    supplier: 'FreshFarms',
    name: 'Organic Whole Milk',
    description: '1 Litre',
    price: 2.49,
    originalPrice: 3.00,
    unitPrice: '2.49/L',
    image: '/images/product-milk.svg',
    pricingOptions: 3,
  },
  {
    id: 'new-6',
    supplier: 'NutriGrain',
    name: 'Brown Basmati Rice',
    description: '2 kg',
    options: 'More sizes',
    price: 4.99,
    originalPrice: 5.80,
    unitPrice: '2.50/kg',
    image: '/images/product-rice.svg',
    pricingOptions: 3,
  },
  {
    id: 'new-7',
    supplier: 'LLPsuperstore',
    name: 'Coca-Cola Cherry Flavour',
    description: '6 x 330ml',
    options: 'Options: 3 sizes, 2 Flavours',
    price: 3.99,
    originalPrice: 4.80,
    unitPrice: '0.67/can',
    image: '/images/product-cocacola.svg',
    pricingOptions: 6,
  },
];

/* ── Categories + subcategories ── */

export const categories: Category[] = [
  {
    id: 'warehouse',
    name: 'Warehouse',
    subcategories: [
      { id: 'ws-all', name: 'Shop All' },
      { id: 'ws-bulk', name: 'Bulk Items' },
      { id: 'ws-cleaning', name: 'Cleaning Supplies' },
    ],
  },
  {
    id: 'drinks',
    name: 'Drinks',
    subcategories: [
      { id: 'dr-all', name: 'Shop All' },
      { id: 'dr-beers', name: 'Beers' },
      { id: 'dr-wines', name: 'Wines and Sparkling Wines' },
      { id: 'dr-white', name: 'White Drinks' },
      { id: 'dr-fernet', name: 'Fernet and Aperitifs' },
      { id: 'dr-soft', name: 'Soft Drinks' },
      { id: 'dr-water', name: 'Water' },
      { id: 'dr-flavoured', name: 'Flavoured Water' },
      { id: 'dr-juices', name: 'Juices' },
      { id: 'dr-isotonic', name: 'Isotonic Drinks' },
      { id: 'dr-energy', name: 'Energising Drinks' },
      { id: 'dr-others', name: 'Others' },
    ],
  },
  {
    id: 'dairy',
    name: 'Dairy and Fresh Products',
    subcategories: [
      { id: 'da-all', name: 'Shop All' },
      { id: 'da-milk', name: 'Milk' },
      { id: 'da-cheese', name: 'Cheese' },
      { id: 'da-yogurt', name: 'Yogurt' },
    ],
  },
  {
    id: 'frozen',
    name: 'Frozen Products',
    subcategories: [
      { id: 'fr-all', name: 'Shop All' },
      { id: 'fr-icecream', name: 'Ice Cream' },
      { id: 'fr-meals', name: 'Frozen Meals' },
    ],
  },
  {
    id: 'cleaning',
    name: 'Cleaning',
    subcategories: [
      { id: 'cl-all', name: 'Shop All' },
      { id: 'cl-laundry', name: 'Laundry' },
      { id: 'cl-kitchen', name: 'Kitchen' },
    ],
  },
  {
    id: 'meat',
    name: 'Meat and Fish',
    subcategories: [
      { id: 'mt-all', name: 'Shop All' },
      { id: 'mt-beef', name: 'Beef' },
      { id: 'mt-chicken', name: 'Chicken' },
      { id: 'mt-fish', name: 'Fish' },
    ],
  },
  {
    id: 'fruits',
    name: 'Fruits and Vegetables',
    subcategories: [
      { id: 'fv-all', name: 'Shop All' },
      { id: 'fv-fruits', name: 'Fruits' },
      { id: 'fv-vegetables', name: 'Vegetables' },
    ],
  },
  {
    id: 'bakery',
    name: 'Bakery',
    subcategories: [
      { id: 'bk-all', name: 'Shop All' },
      { id: 'bk-bread', name: 'Bread' },
      { id: 'bk-pastry', name: 'Pastries' },
    ],
  },
  {
    id: 'perfumery',
    name: 'Perfumery',
    subcategories: [
      { id: 'pf-all', name: 'Shop All' },
    ],
  },
  {
    id: 'baby',
    name: 'Baby World',
    subcategories: [
      { id: 'bw-all', name: 'Shop All' },
    ],
  },
  {
    id: 'others',
    name: 'Others',
    subcategories: [
      { id: 'ot-all', name: 'Shop All' },
    ],
  },
  {
    id: 'pets',
    name: 'Pet Supplies',
    subcategories: [
      { id: 'ps-all', name: 'Shop All' },
    ],
  },
  {
    id: 'books',
    name: 'Books and Stationery',
    subcategories: [
      { id: 'bs-all', name: 'Shop All' },
    ],
  },
];

/* ── Search/Category product listing (shared pool) ── */

export const categoryProducts: HomeProduct[] = [
  {
    id: 'cat-1',
    supplier: 'LLPsuperstore',
    name: 'Coca-Cola Original Taste',
    description: '24 x 330ml',
    options: 'Options: 3 sizes, 2 Flavours',
    price: 8.99,
    originalPrice: 12.50,
    unitPrice: '11.5/unit',
    image: '/images/product-cocacola.svg',
    pricingOptions: 6,
  },
  {
    id: 'cat-2',
    supplier: 'AquaPure',
    name: 'Natural Spring Water',
    description: '6 x 1.5L',
    options: 'More sizes',
    price: 3.50,
    originalPrice: 4.20,
    unitPrice: '0.39/L',
    image: '/images/product-water.svg',
    pricingOptions: 4,
  },
  {
    id: 'cat-3',
    supplier: 'Del Monte',
    name: 'Orange Juice, No Pulp',
    description: '1 Litre',
    options: 'More flavours',
    price: 2.99,
    originalPrice: 3.80,
    unitPrice: '2.99/L',
    image: '/images/product-juice.svg',
    pricingOptions: 5,
  },
  {
    id: 'cat-4',
    supplier: 'FreshFarms',
    name: 'Full Cream Milk',
    description: '2 Litres',
    options: 'More sizes',
    price: 2.15,
    originalPrice: 2.60,
    unitPrice: '1.08/L',
    image: '/images/product-milk.svg',
    pricingOptions: 3,
  },
  {
    id: 'cat-5',
    supplier: 'LLPsuperstore',
    name: 'Coca-Cola Zero Sugar',
    description: '12 x 330ml',
    options: 'Options: 3 sizes, 2 Flavours',
    price: 5.99,
    originalPrice: 7.20,
    unitPrice: '0.50/can',
    image: '/images/product-cocacola.svg',
    pricingOptions: 6,
  },
  {
    id: 'cat-6',
    supplier: 'AquaPure',
    name: 'Sparkling Mineral Water',
    description: '12 x 500ml',
    options: 'More sizes',
    price: 4.99,
    originalPrice: 6.00,
    unitPrice: '0.42/bottle',
    image: '/images/product-water.svg',
    pricingOptions: 4,
  },
  {
    id: 'cat-7',
    supplier: 'Del Monte',
    name: 'Tropical Fruit Juice Blend',
    description: '1.5 Litres',
    options: 'More flavours',
    price: 3.79,
    originalPrice: 4.50,
    unitPrice: '2.53/L',
    image: '/images/product-juice.svg',
    pricingOptions: 5,
  },
  {
    id: 'cat-8',
    supplier: 'FreshFarms',
    name: 'Organic Whole Milk',
    description: '1 Litre',
    price: 2.49,
    originalPrice: 3.00,
    unitPrice: '2.49/L',
    image: '/images/product-milk.svg',
    pricingOptions: 3,
  },
  {
    id: 'cat-9',
    supplier: 'LLPsuperstore',
    name: 'Coca-Cola Cherry Flavour',
    description: '6 x 330ml',
    options: 'Options: 3 sizes, 2 Flavours',
    price: 3.99,
    originalPrice: 4.80,
    unitPrice: '0.67/can',
    image: '/images/product-cocacola.svg',
    pricingOptions: 6,
  },
  {
    id: 'cat-10',
    supplier: 'Del Monte',
    name: 'Apple Juice, 100% Pure',
    description: '1 Litre',
    options: 'More flavours',
    price: 2.49,
    originalPrice: 3.20,
    unitPrice: '2.49/L',
    image: '/images/product-juice.svg',
    pricingOptions: 5,
  },
  {
    id: 'cat-11',
    supplier: 'AquaPure',
    name: 'Still Mineral Water',
    description: '24 x 500ml',
    options: 'More sizes',
    price: 6.99,
    originalPrice: 8.50,
    unitPrice: '0.29/bottle',
    image: '/images/product-water.svg',
    pricingOptions: 4,
  },
  {
    id: 'cat-12',
    supplier: 'FreshFarms',
    name: 'Semi-Skimmed Milk',
    description: '6 x 1L',
    options: 'More sizes',
    price: 5.49,
    originalPrice: 6.50,
    unitPrice: '0.92/L',
    image: '/images/product-milk.svg',
    pricingOptions: 3,
  },
];

/* ── Beverages subcategories (for search page demo) ── */

export const beverageSubcategories: SubCategory[] = [
  { id: 'bev-water', name: 'Water' },
  { id: 'bev-soda', name: 'Soda' },
  { id: 'bev-juices', name: 'Juices' },
  { id: 'bev-kids', name: 'Kids Drink & Juice Box' },
  { id: 'bev-sports', name: 'Sport Drinks' },
  { id: 'bev-tea', name: 'Tea' },
  { id: 'bev-mix', name: 'Drink Mix' },
];
